services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - frontend

  node-app:
    build:
      context: ./node-app
    container_name: node-app
    volumes:
      - ./node-app:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - mysql-db
    networks:
      - frontend
      - backend

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  frontend:
  backend: